name: yolo
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.10  # or your preferred version
  - cuda-toolkit
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - ultralytics
      - opencv-python
      - pyrealsense2
