FROM ubuntu:20.04

LABEL maintainer="srinath.bhamidipati@research.iiit.ac.in"

ENV TZ=Asia/Kolkata
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 \
    DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        tzdata locales curl ca-certificates lsb-release software-properties-common \
        build-essential python3-pip python3-dev python3-venv python3-setuptools \
        git wget gnupg sudo cmake libssl-dev libusb-1.0-0-dev pkg-config \
        libglfw3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    locale-gen en_US.UTF-8 && update-locale LANG=en_US.UTF-8 && \
    rm -rf /var/lib/apt/lists/*

ENV CUDA_VERSION=11.4 \
    PATH=/usr/local/cuda/bin:$PATH \
    LD_LIBRARY_PATH=/usr/local/cuda/lib64:${LD_LIBRARY_PATH:-}

ARG CMAKE_VERSION=3.27.8
RUN curl -sSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-aarch64.sh -o cmake.sh && \
    chmod +x cmake.sh && ./cmake.sh --skip-license --prefix=/usr/local && rm cmake.sh

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    apt-get update && apt-get install -y ros-noetic-ros-base && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash rosuser && \
    echo "rosuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    chown -R rosuser:rosuser /home/rosuser /opt/ros

WORKDIR /home/rosuser
RUN git clone --branch v2.56.2 https://github.com/IntelRealSense/librealsense.git

WORKDIR /home/rosuser/librealsense
RUN mkdir -p /etc/udev/rules.d && \
    mkdir build && cd build && \
    cmake ../ && \
    make clean && \
    make && \
    make install

RUN apt-get update && \
    apt-get install -y ros-noetic-realsense2-camera ros-noetic-ddynamic-reconfigure && \
    rm -rf /var/lib/apt/lists/*

USER rosuser
WORKDIR /home/rosuser
RUN pip3 install dill
RUN echo "source /opt/ros/noetic/setup.bash" >> /home/rosuser/.bashrc

CMD ["/bin/bash"]
