name: yolo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - opencv
  - matplotlib
  - pyzmq
  - cudatoolkit=11.8
  - pip:
      - torch
      - torchvision
      - torchaudio
      - ultralytics
      - pyrealsense2
