name: yolo
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - numpy
  - opencv
  - matplotlib
  - pip:
      - torch
      - torchvision
      - torchaudio
      - ultralytics
      - pyrealsense2
